Use lock on CTI profile POST
nethesis/nethvoice-wizard-restapi pull request #169
Opened 2021-05-17 14:24 UTC by Stell0

Use lock on on CTI/profile POST to avoid race conditions.
Return 500 if lock can't be acquired
https://github.com/nethesis/dev/issues/5979

2021-05-17 14:33 UTC, SebastianMB-IT approved these changes

2021-05-17 14:39 UTC, gsanchietti requested changes

2021-05-17 14:39 UTC, gsanchietti commented on root/var/www/html/freepbx/rest/modules/cti.php
> +        file_put_contents($sharedLock,time());
Please, ensure the `/var/run/nethvoice` directory exists and it's writable

2021-05-17 14:39 UTC, gsanchietti commented on root/var/www/html/freepbx/rest/modules/cti.php
> +	unlink($sharedLock);
Fix identation

2021-05-18 08:06 UTC, gsanchietti approved these changes

2021-05-19 09:27 UTC, merged